name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push-docker:
    permissions:
      contents: write      # Required for auto-versioning (creating Git tags)
      id-token: write      # Required for attestations (public repos only)
      attestations: write  # Required for build provenance (public repos only)
    uses: cyberralf83/My-Github-Actions-Workflows/.github/workflows/docker-build-push.yml@main
    with:
      image-name: ambient-weather-webcam-uploader-docker
      docker-username: 'ralf83'
      dockerfile-path: './Dockerfile'
      context: '.'
      platforms: 'linux/amd64,linux/arm64'
    secrets:
      docker-token: ${{ secrets.DOCKER_TOKEN }}
